### ISSUE TITLE
loadImage 

### ISSUE THREAD

**Issue by Debb878** [Debb878/finals#1]
I got an error and I don't know where to go to fix the problem. 
![Screenshot (3)](https://user-images.githubusercontent.com/59706190/76818363-abb05d80-67c2-11ea-96ee-a044b0de1fde.png)

**Comment by jmej** [comment]
Ah I missed this before! That is a CORS error which will come up if you aren't running the site with a webserver. Try typing live-server from the command line in your project folder to get it up and running!
